openapi: 3.0.0
info:
  title: Scalingo-Backend-Test
  description: API documentation
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Ping the server
      description: Checks the server status with a simple ping.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "pong"

  /repos:
    get:
      summary: Get a list of the most recent repositories created on GitHub
      description: Fetches repository details such as name, owner, license, and language breakdown.
      parameters:
        - in: query
          name: language
          schema:
            type: string
          description: Filter by programming language
          example: html
        - in: query
          name: license
          schema:
            type: string
          description: Filter by license type
          example: apache-2.0
      responses:
        '200':
          description: Repository information
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "leaflet"
                  owner:
                    type: string
                    example: "laurisasastoque"
                  url:
                    type: string
                    format: uri
                    example: "https://api.github.com/repos/laurisasastoque/leaflet"
                  description:
                    type: string
                    example: "A leaflet project in html "
                  license:
                    type: string
                    example: "mit"
                  language:
                    type: object
                    additionalProperties:
                      type: integer
                    example:
                      go: 7683
                      javascript: 369423
components: {}
